name: intake-geopandas
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - intake>=0.2
  - geopandas
  - dask
  - pandas
  - aiohttp
  - pyarrow>=5.0.0
  - requests
  - pytest
  - pytest-cov
