name: CI

on:
  push:
    branches: "*"
  pull_request:
    branches: master

jobs:
  test:
    name: ${{ matrix.CONDA_ENV }}-pytest
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        CONDA_ENV: [py37, py38, pip]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: false
          activate-environment: test_env
          environment-file: conda/environment-${{ matrix.CONDA_ENV }}.yaml

      - name: pip-install
        shell: bash -l {0}
        run: |
          pip install -e . --no-deps
      - name: Run Tests
        shell: bash -l {0}
        run: |
          pytest --verbose --cov=intake_geopandas
